export const ADMIN_PROFILE = {
  id: "adm-001",
  name: "TS. Eleanor Vance",
  title: "Super Admin",
  code: "LIB-ADM-001",
  department: "Ban Giám đốc & Điều hành Hệ thống",
  email: "eleanor.vance@library.edu.vn",
  avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
};

export const ADMIN_KPI_METRICS = {
  authorizedPersonnel: {
    registered: 6,
    active: 4,
    auditText: "Tất cả vai trò được kiểm toán",
  },
  borrowingTiers: {
    activeClasses: 5,
    loanCapRange: "3 – 25 cuốn",
  },
  overdueFine: {
    dailyRate: 5000,
    dailyRateText: "5.000 đ / ngày",
    maxCapText: "Tối đa: 250.000 đ",
    graceText: "Ân hạn: 2 ngày",
  },
  physicalStacks: {
    capacityPercent: 75,
    currentCount: 1239,
    maxCount: 1650,
  },
};

export const INITIAL_EMPLOYEES = [
  {
    id: "emp-1",
    name: "TS. Eleanor Vance",
    email: "eleanor.vance@library.edu.vn",
    code: "LIB-ADM-001",
    role: "Super Admin",
    department: "Ban Giám đốc & Điều hành",
    status: "Active",
    permissionsCount: 8,
    lastActive: "2026-09-12 08:42 AM",
    initials: "EV",
  },
  {
    id: "emp-2",
    name: "Marcus Chen",
    email: "marcus.chen@library.edu.vn",
    code: "LIB-SRL-014",
    role: "Librarian",
    department: "Dịch vụ Thư viện & Tra cứu",
    status: "Active",
    permissionsCount: 5,
    lastActive: "2026-09-11 04:15 PM",
    initials: "MC",
  },
  {
    id: "emp-3",
    name: "Amina Al-Mansoor",
    email: "amina.mansoor@library.edu.vn",
    code: "LIB-CAT-022",
    role: "Cataloger",
    department: "Biên mục & Xử lý Kỹ thuật",
    status: "Active",
    permissionsCount: 3,
    lastActive: "2026-09-12 07:10 AM",
    initials: "AA",
  },
  {
    id: "emp-4",
    name: "Julian Hayes",
    email: "julian.hayes@library.edu.vn",
    code: "LIB-CIR-038",
    role: "Circulation Staff",
    department: "Lưu thông & Phục vụ Độc giả",
    status: "Active",
    permissionsCount: 2,
    lastActive: "2026-09-10 11:30 AM",
    initials: "JH",
  },
  {
    id: "emp-5",
    name: "Sarah Lindqvist",
    email: "sarah.l@library.edu.vn",
    code: "LIB-CTR-045",
    role: "Circulation Staff",
    department: "Lưu thông & Phục vụ Độc giả",
    status: "Inactive",
    permissionsCount: 1,
    lastActive: "2026-08-14 02:22 PM",
    initials: "SL",
  },
  {
    id: "emp-6",
    name: "David K. Osei",
    email: "david.osei@library.edu.vn",
    code: "LIB-CAT-029",
    role: "Cataloger",
    department: "Bộ sưu tập Đặc biệt & Lưu trữ",
    status: "Suspended",
    permissionsCount: 0,
    lastActive: "2026-07-30 09:05 AM",
    initials: "DK",
  },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: "tx-981",
    timestamp: "2026-09-12 05:22:18",
    actor: "TS. Eleanor Vance",
    actorCode: "LIB-ADM-001",
    actorRole: "Super Admin",
    eventTag: "CẤU HÌNH PHÍ PHẠT",
    eventCategory: "fine",
    eventTagType: "warning",
    target: "Biểu phí quá hạn & Lịch trình phạt",
    details: "Điều chỉnh thời gian ân hạn thành 2 ngày; xác nhận phí quá hạn 5.000 đ/ngày.",
    ip: "192.168.1.10",
  },
  {
    id: "tx-987",
    timestamp: "2026-09-12 04:15:02",
    actor: "TS. Eleanor Vance",
    actorCode: "LIB-ADM-001",
    actorRole: "Super Admin",
    eventTag: "QUY ĐỊNH MƯỢN TRẢ",
    eventCategory: "rules",
    eventTagType: "purple",
    target: "Chính sách mượn sách Giảng viên",
    details: "Mở rộng thời gian mượn tiêu chuẩn cho Giảng viên cơ hữu lên 90 ngày với 4 lần gia hạn.",
    ip: "192.168.1.10",
  },
  {
    id: "tx-985",
    timestamp: "2026-09-11 16:40:55",
    actor: "Marcus Chen",
    actorCode: "LIB-SRL-014",
    actorRole: "Senior Librarian",
    eventTag: "THAY ĐỔI KỆ SÁCH",
    eventCategory: "shelves",
    eventTagType: "cyan",
    target: "Kệ sách FL1-EW-MATH01",
    details: "Đánh dấu kệ mật độ cao (99% sức chứa); đề xuất chuyển sách tràn sang Dãy B.",
    ip: "192.168.1.44",
  },
  {
    id: "tx-984",
    timestamp: "2026-09-11 11:12:30",
    actor: "TS. Eleanor Vance",
    actorCode: "LIB-ADM-001",
    actorRole: "Super Admin",
    eventTag: "KHÓA TÀI KHOẢN",
    eventCategory: "employee",
    eventTagType: "danger",
    target: "Sarah Lindqvist (LIB-CIR-045)",
    details: "Chuyển tài khoản sang trạng thái tạm ngưng do nghỉ phép nghiên cứu.",
    ip: "192.168.1.10",
  },
  {
    id: "tx-983",
    timestamp: "2026-09-10 14:02:18",
    actor: "TS. Eleanor Vance",
    actorCode: "LIB-ADM-001",
    actorRole: "Super Admin",
    eventTag: "TẠO NHÂN VIÊN",
    eventCategory: "employee",
    eventTagType: "success",
    target: "Julian Hayes (LIB-CIR-038)",
    details: "Cấp tài khoản nhân viên lưu thông với quyền truy cập quầy phục vụ tiêu chuẩn.",
    ip: "192.168.1.10",
  },
];

export const INITIAL_BORROWING_RULES = [
  {
    id: "undergrad",
    name: "Sinh viên Đại học",
    tierCode: "UNDERGRADUATE",
    description: "Sinh viên đang theo học hệ Đại học chính quy tất cả các khoa.",
    maxBooks: 6,
    loanPeriodDays: 14,
    renewals: 2,
    gracePeriodDays: 2,
    holdShelfDays: 3,
    updatedAt: "2026-08-15",
  },
  {
    id: "postgrad",
    name: "Học viên Cao học & Thạc sĩ",
    tierCode: "POSTGRADUATE",
    description: "Học viên Cao học, Thạc sĩ và Nghiên cứu sinh Tiến sĩ.",
    maxBooks: 12,
    loanPeriodDays: 28,
    renewals: 3,
    gracePeriodDays: 3,
    holdShelfDays: 5,
    updatedAt: "2026-08-15",
  },
  {
    id: "faculty",
    name: "Giảng viên & Nghiên cứu viên",
    tierCode: "FACULTY",
    description: "Giảng viên cơ hữu, thỉnh giảng và cán bộ nghiên cứu viện.",
    maxBooks: 25,
    loanPeriodDays: 90,
    renewals: 4,
    gracePeriodDays: 7,
    holdShelfDays: 7,
    updatedAt: "2026-08-20",
  },
  {
    id: "researcher",
    name: "Nghiên cứu viên thỉnh giảng",
    tierCode: "RESEARCHER",
    description: "Cộng tác viên nghiên cứu và đối tác học thuật liên kết.",
    maxBooks: 15,
    loanPeriodDays: 45,
    renewals: 3,
    gracePeriodDays: 4,
    holdShelfDays: 5,
    updatedAt: "2026-08-18",
  },
  {
    id: "community",
    name: "Độc giả Cộng đồng & Cựu SV",
    tierCode: "GENERAL_PUBLIC",
    description: "Cựu sinh viên đã đăng ký và độc giả ngoài có thẻ thư viện.",
    maxBooks: 3,
    loanPeriodDays: 10,
    renewals: 1,
    gracePeriodDays: 1,
    holdShelfDays: 2,
    updatedAt: "2026-08-10",
  },
];

export const INITIAL_FINE_SETTINGS = {
  dailyFineRate: 5000,
  maxOverdueCap: 250000,
  gracePeriodDays: 2,
  lostMultiplier: 1.5,
  standardProcessingFee: 120000,
  cashierWaiverLimit: 100000,
  enableWaivers: true,
  lastAdjusted: "2026-09-01",
};

export const INITIAL_CATEGORIES = [
  { id: "cat-1", dewey: "000-099", name: "Khoa học máy tính & Thông tin", bookCount: 1420, activeRules: "Tiêu chuẩn" },
  { id: "cat-2", dewey: "100-199", name: "Triết học & Tâm lý học", bookCount: 680, activeRules: "Tiêu chuẩn" },
  { id: "cat-3", dewey: "300-399", name: "Khoa học xã hội & Kinh tế", bookCount: 2150, activeRules: "Tham khảo đặc biệt" },
  { id: "cat-4", dewey: "500-599", name: "Khoa học tự nhiên & Toán học", bookCount: 1890, activeRules: "Hạn chế mượn ngoài" },
  { id: "cat-5", dewey: "600-699", name: "Công nghệ & Y học", bookCount: 3100, activeRules: "Tiêu chuẩn" },
  { id: "cat-6", dewey: "800-899", name: "Văn học & Ngôn ngữ", bookCount: 4200, activeRules: "Tiêu chuẩn" },
];

export const INITIAL_AUTHORS = [
  {
    id: "auth-1",
    name: "Donald E. Knuth",
    nationality: "American",
    years: "1938 - Hiện tại",
    genre: "Computer Science",
    bio: "Tác giả của bộ sách kinh điển 'The Art of Computer Programming' và người sáng tạo ra hệ thống TeX.",
    holdingsCount: 14,
  },
  {
    id: "auth-2",
    name: "Ada Lovelace",
    nationality: "British",
    years: "1815 - 1852",
    genre: "Mathematical Computation",
    bio: "Lập trình viên máy tính đầu tiên trên thế giới, tiên phong về tính toán giải thuật với Charles Babbage.",
    holdingsCount: 4,
  },
  {
    id: "auth-3",
    name: "Richard P. Feynman",
    nationality: "American",
    years: "1918 - 1988",
    genre: "Quantum Physics",
    bio: "Nhà vật lý đoạt giải Nobel, nổi tiếng với điện động lực học lượng tử và bộ sách Feynman Lectures on Physics.",
    holdingsCount: 18,
  },
  {
    id: "auth-4",
    name: "Gabriel García Márquez",
    nationality: "Colombian",
    years: "1927 - 2014",
    genre: "Magical Realism",
    bio: "Nhà văn đoạt giải Nobel Văn học, đại diện tiêu biểu của chủ nghĩa hiện thực huyền ảo và tác giả 'Trăm năm cô đơn'.",
    holdingsCount: 12,
  },
  {
    id: "auth-5",
    name: "Yuval Noah Harari",
    nationality: "Israeli",
    years: "1976 - Hiện tại",
    genre: "Macro-History",
    bio: "Nhà sử học, trí thức công cộng và tác giả của các cuốn sách bán chạy toàn cầu như 'Sapiens: Lược sử loài người'.",
    holdingsCount: 8,
  },
];

export const INITIAL_PUBLISHERS = [
  {
    id: "pub-1",
    vendorCode: "MIT-PRESS",
    name: "MIT Press Publications",
    country: "United States",
    repName: "Rachel Davenport",
    repEmail: "acquisitions@mitpress.edu",
    phone: "+1 (617) 253-5646",
    address: "One Broadway, Floor 12, Cambridge, MA",
    activeContracts: 48,
    status: "ACTIVE",
  },
  {
    id: "pub-2",
    vendorCode: "OXF-ACAD",
    name: "Oxford University Press",
    country: "United Kingdom",
    repName: "Sir Alistair Montgomery",
    repEmail: "institutional.orders@oup.com",
    phone: "+44 (0)1865 556767",
    address: "Great Clarendon St, Oxford OX2 6DP",
    activeContracts: 86,
    status: "ACTIVE",
  },
  {
    id: "pub-3",
    vendorCode: "SPR-NAT",
    name: "Springer Nature Academic",
    country: "Germany",
    repName: "Heike Gruber",
    repEmail: "libraryrelations@springernature.com",
    phone: "+49 6221 487 0",
    address: "Tiergartenstraße 17, 69121 Heidelberg",
    activeContracts: 112,
    status: "ACTIVE",
  },
  {
    id: "pub-4",
    vendorCode: "OREIL-MEDIA",
    name: "O'Reilly Media, Inc.",
    country: "United States",
    repName: "Kevin Miller",
    repEmail: "corporate@oreilly.com",
    phone: "+1 (707) 827-7000",
    address: "1005 Gravenstein Highway North, Sebastopol, CA",
    activeContracts: 64,
    status: "ACTIVE",
  },
];

export const INITIAL_DETAILED_SHELVES = [
  {
    id: "sh-1",
    code: "FL1-NW-CS01",
    floor: "Floor 1",
    location: "Khu Bắc · Khoa học Máy tính",
    taxonomy: "Computer Science & Software Systems",
    currentLoad: 215,
    maxCapacity: 250,
    occupancy: 86,
    freeSlots: 35,
    status: "Near Capacity",
    statusType: "warning",
  },
  {
    id: "sh-2",
    code: "FL1-NW-CS02",
    floor: "Floor 1",
    location: "Khu Bắc · Khoa học Máy tính",
    taxonomy: "Computer Science & Software Systems",
    currentLoad: 180,
    maxCapacity: 250,
    occupancy: 72,
    freeSlots: 70,
    status: "Optimal Load",
    statusType: "success",
  },
  {
    id: "sh-3",
    code: "FL1-EW-MATH01",
    floor: "Floor 1",
    location: "Khu Đông · Toán học & Thống kê",
    taxonomy: "Mathematics & Statistical Sciences",
    currentLoad: 198,
    maxCapacity: 200,
    occupancy: 99,
    freeSlots: 2,
    status: "Capacity Critical (Full)",
    statusType: "danger",
  },
  {
    id: "sh-4",
    code: "FL2-SW-PHYS01",
    floor: "Floor 2",
    location: "Khu Nam · Vật lý & Cơ học",
    taxonomy: "Physics & Classical Mechanics",
    currentLoad: 140,
    maxCapacity: 200,
    occupancy: 70,
    freeSlots: 60,
    status: "Optimal Load",
    statusType: "success",
  },
  {
    id: "sh-5",
    code: "FL2-CW-LIT01",
    floor: "Floor 2",
    location: "Khu Trung tâm · Văn học Thế giới",
    taxonomy: "World Literature & Poetry",
    currentLoad: 165,
    maxCapacity: 220,
    occupancy: 75,
    freeSlots: 55,
    status: "Optimal Load",
    statusType: "success",
  },
  {
    id: "sh-6",
    code: "FL3-AR-HIST01",
    floor: "Floor 3",
    location: "Khu Lưu trữ · Lịch sử & Địa lý",
    taxonomy: "History, Civilization & Geography",
    currentLoad: 184,
    maxCapacity: 200,
    occupancy: 92,
    freeSlots: 16,
    status: "Near Capacity",
    statusType: "warning",
  },
];
