export const READER_PROFILE = {
  name: "Lê Hoàng Nam",
  roleTitle: "Độc giả SV-2024",
  cardNumber: "VN-EDU-2024-8849",
  status: "Đang hoạt động",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  currentBorrows: 3,
  maxBorrows: 5,
  nearestDueDate: "25/11/2024",
  daysRemaining: 3,
  unpaidFine: "0 đ",
  accountStatus: "Tài khoản chuẩn mực",
};

export const DUE_ALERT_DATA = {
  bookTitle: "Nhập môn Cấu trúc Dữ liệu & Giải thuật",
  deadlineTime: "17:00 ngày 25/11/2024",
  finePerDay: "5.000 đ/ngày",
};

export const BORROWED_BOOKS = [
  {
    id: "b1",
    title: "Cấu trúc Dữ liệu & Giải thuật",
    author: "Đỗ Xuân Lôi",
    barcode: "BC-DS-2024-0092",
    borrowDate: "11/11/2024",
    dueDate: "25/11/2024",
    tagText: "Còn 3 ngày",
    tagType: "warning",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=300&auto=format&fit=crop&q=80",
    canRenew: true,
    renewDays: 14,
  },
  {
    id: "b2",
    title: "Artificial Intelligence: Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    barcode: "BC-AI-2023-1184",
    borrowDate: "19/11/2024",
    dueDate: "03/12/2024",
    tagText: "Còn 11 ngày",
    tagType: "success",
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80",
    canRenew: true,
    renewDays: 7,
  },
  {
    id: "b3",
    title: "Kinh tế Học Vi mô Căn bản",
    author: "N. Gregory Mankiw",
    barcode: "BC-EC-2022-7721",
    borrowDate: "07/11/2024",
    dueDate: "21/11/2024",
    accumulatedFine: "5.000 VND",
    tagText: "Quá hạn 1 ngày",
    tagType: "danger",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&auto=format&fit=crop&q=80",
    canRenew: false,
    isOverdue: true,
  },
];

export const CATALOG_BOOKS = [
  {
    id: "c1",
    title: "Designing Data-Intensive Applications",
    subTitle: "Nhiết kế mẫu kiến trúc phần mềm hệ thống phân tán",
    author: "Martin Kleppmann",
    stockTag: "Còn 4 bản",
    stockStatus: "available",
    shelfLocation: "Kệ K-03 / Tầng 2",
    rating: 4.9,
    reviewCount: 38,
    description: "Cẩm nang toàn diện về kiến trúc dữ liệu lớn, độ tin cậy, khả năng mở rộng và tính bảo trì cho hệ thống Microservices hiện đại.",
    isbn: "978-1449373320",
    coverImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&auto=format&fit=crop&q=80",
    category: "Công nghệ thông tin",
    isEbook: true,
  },
  {
    id: "c2",
    title: "Machine Learning Yearning",
    subTitle: "Giáo trình Trí tuệ nhân tạo và Máy học ứng dụng",
    author: "Andrew Ng",
    stockTag: "Hết sách - Có thể đặt trước",
    stockStatus: "out_of_stock",
    shelfLocation: "Kệ K-08 / Tầng 3",
    rating: 4.8,
    reviewCount: 52,
    description: "Chiến lược định hướng cấu trúc dự án Trí tuệ Nhân tạo, cách sửa lỗi mô hình và tối ưu hóa quy trình huấn luyện thực tế.",
    isbn: "978-0578401386",
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&auto=format&fit=crop&q=80",
    category: "Công nghệ thông tin",
    isEbook: false,
    queueCount: 1,
  },
  {
    id: "c3",
    title: "Phi Lý Trí (Predictably Irrational)",
    subTitle: "Lý thuyết hành vi ứng dụng trong thực tiễn",
    author: "Dan Ariely",
    stockTag: "Còn 2 bản",
    stockStatus: "available",
    shelfLocation: "Kệ E-12 / Tầng 1",
    rating: 4.7,
    reviewCount: 29,
    description: "Khảo sát thực nghiệm về các quyết định tài chính và đời sống tưởng chừng logic nhưng thực chất bị chi phối bởi yếu tố phi lý trí.",
    isbn: "978-6061353246",
    coverImage: "https://images.unsplash.com/photo-1509021436468-d5103e3f74d3?w=400&auto=format&fit=crop&q=80",
    category: "Kinh tế",
    isEbook: true,
  },
  {
    id: "c4",
    title: "The Art of Computer Programming: Vol 1",
    subTitle: "Nghệ thuật lập trình máy tính - Tập 1: Thuật toán cơ bản",
    author: "Donald E. Knuth",
    stockTag: "Còn 1 bản",
    stockStatus: "available",
    shelfLocation: "Kệ K-01 / Phòng Đọc",
    rating: 5.0,
    reviewCount: 64,
    description: "Tác phẩm kinh điển nền tảng của khoa học máy tính toàn cầu, khảo sát toàn diện các thuật toán và cấu trúc dữ liệu cốt lõi.",
    isbn: "978-0201896831",
    coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&auto=format&fit=crop&q=80",
    category: "Công nghệ thông tin",
    isEbook: false,
  },
];

export const FILTER_OPTIONS = {
  majors: ["Công nghệ thông tin", "Kinh tế", "Ngoại ngữ", "Điện - Điện tử", "Cơ khí"],
  authors: ["Tác giả (Toàn bộ)", "Martin Kleppmann", "Andrew Ng", "Dan Ariely", "Donald E. Knuth", "Đỗ Xuân Lôi"],
  publishYears: ["Năm xuất bản", "2024", "2023", "2022", "2021", "Trước 2020"],
};
