server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: library-management
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  jackson:
    default-property-inclusion: non_null

jwt:
  signerKey: ${JWT_SIGNER_KEY:kF5zVTO0INk5i79nW8mzlUfpqPm1W31AuS30GPwOtM4IFpnZEE9dTYRjXkxKYLp4H2Ah3W6o5Z5PHO4hvmRE1b}
  valid-duration: ${JWT_VALID_DURATION:900}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000}

logging:
  level:
    org.hibernate.SQL: DEBUG